# Generated by Django 5.1.2 on 2024-12-04 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='library',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='section',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='catalog',
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name': 'Библиотека', 'verbose_name_plural': 'Библиотеки'},
        ),
        migrations.RenameField(
            model_name='library',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='library',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='library',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Название библиотеки'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LibraryDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField(max_length=255, verbose_name='База данных')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='library_service.library')),
            ],
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
    ]
