# Generated by Django 5.1.2 on 2024-12-04 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_service', '0002_remove_catalog_library_remove_catalog_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarydatabase',
            options={'verbose_name': 'База данных библиотеки', 'verbose_name_plural': 'Базы данных библиотек'},
        ),
    ]
