# Generated by Django 5.1.2 on 2024-12-04 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_service', '0003_alter_librarydatabase_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='name',
        ),
    ]
