# Generated by Django 5.1.2 on 2024-12-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_service', '0004_remove_library_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='confirmed_at',
            new_name='date',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='handed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
