# Generated by Django 5.1.2 on 2025-01-23 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_service', '0005_rename_confirmed_at_history_date_orderitem_handed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='library_service.basket'),
        ),
    ]
