# Generated by Django 5.1.2 on 2025-01-29 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_service', '0008_alter_orderhistory_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_to_return',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_service.order'),
        ),
    ]
