# Generated by Django 5.1.2 on 2025-01-29 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_service', '0009_orderitem_order_to_return'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_to_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_service.order'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='campus_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID кампуса'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mira_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID mira'),
        ),
    ]
