# Generated by Django 5.1.2 on 2025-01-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_service', '0010_remove_orderhistory_staff_id_orderhistory_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='book_id',
            field=models.CharField(default='ISTU_1', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='exemplar_id',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
