# Generated by Django 5.1.2 on 2025-01-31 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_service', '0011_orderitem_book_id_alter_orderitem_exemplar_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basketitem',
            unique_together={('basket', 'book_id')},
        ),
    ]
