# Generated by Django 5.1.2 on 2025-02-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_service', '0012_alter_basketitem_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='handed',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='returned',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('ordered', 'Заказана'), ('handed', 'Выдана'), ('returned', 'Возвращена'), ('cancelled', 'Заказ отменен')], default='ordered', max_length=255),
        ),
    ]
