# Generated by Django 5.1.2 on 2025-02-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_service', '0013_alter_userprofile_user'),
        ('library_service', '0013_remove_orderitem_handed_remove_orderitem_returned_and_more'),
    ]

    operations = [
    ]
