# Generated by Django 5.1.2 on 2025-02-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_service', '0014_merge_20250202_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='handed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='to_return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
