# Generated by Django 5.1.2 on 2025-02-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_service', '0015_orderitem_handed_date_orderitem_returned_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='handed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='to_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
