# Generated by Django 5.0.12 on 2025-03-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("library_service", "0014_remove_librarysettings_library_and_more"),
        ("library_service", "0016_alter_orderitem_handed_date_and_more"),
    ]

    operations = []
