# Generated by Django 5.0.12 on 2025-03-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

        ("library_service", "0017_merge_20250323_1143"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="librarysettings",
            name="id",
        ),
        migrations.AddField(
            model_name="librarysettings",
            name="lock",
            field=models.CharField(default="X", max_length=1, primary_key=True, serialize=False),
        ),
    ]
