# Generated by Django 5.1.2 on 2025-03-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_service", "0018_remove_librarysettings_id_librarysettings_lock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="librarysettings",
            name="holidays",
            field=models.JSONField(default=list, verbose_name="Список календарных выходных"),
        ),
    ]
