# Generated by Django 5.1.2 on 2025-04-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_service", "0020_orderitem_analogous_order_item_orderitem_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.TextField()),
            ],
            options={
                "verbose_name": "Комментарий по заказу",
                "verbose_name_plural": "Комментарии по заказу",
            },
        ),
        migrations.CreateModel(
            name="OrderItemComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.TextField()),
            ],
            options={
                "verbose_name": "Причина отсутствия элемента заказа",
                "verbose_name_plural": "Причины отсутствия элемента заказа",
            },
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="analogous_order_item",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="description",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="exemplar_id",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
