name: Backend job

on:
  pull_request:
    types:
      - synchronize

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
        cache: pip
    
    - name: Install Dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Run Tests
      run: |
        cd backend
        pytest --cov=./ --cov-report xml:coverage.xml
    
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: backend/coverage.xml
        badge: true
        format: markdown
        hide_branch_rate: true
        hide_complexity: true
        output: both

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Run linter
      run: |
        cd backend
        pylint ./